In [4]:
# Imports
import numpy as np
import pandas as pd
import plotly.express as px
import sklearn as sk

In [5]:
"""
import sys
print(sys.executable)
!{sys.executable} -m pip install plotly
"""

'\nimport sys\nprint(sys.executable)\n!{sys.executable} -m pip install plotly\n'

In [6]:
online_shoppers = pd.read_csv('online_shoppers_intention.csv')
online_shoppers

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [7]:
missing_values_df = online_shoppers.isna().sum().reset_index()
missing_values_df.columns = ["Column", "Missing Value Count"]
missing_values_df

                     Column  Missing Value Count
0            Administrative                    0
1   Administrative_Duration                    0
2             Informational                    0
3    Informational_Duration                    0
4            ProductRelated                    0
5   ProductRelated_Duration                    0
6               BounceRates                    0
7                 ExitRates                    0
8                PageValues                    0
9                SpecialDay                    0
10                    Month                    0
11         OperatingSystems                    0
12                  Browser                    0
13                   Region                    0
14              TrafficType                    0
15              VisitorType                    0
16                  Weekend                    0
17                  Revenue                    0

## Features

### Administrative

In [8]:
fig = px.histogram(online_shoppers, x="Administrative", title="Distribution of the Number of Administrative Page Views")

fig.update_layout(
    legend_title_text = "Administrative",
    yaxis_title = "Frequency",
    xaxis_title = "Administrative Page Views"
)

fig.show()

### Administrative_Duration

In [9]:
fig = px.histogram(online_shoppers, x="Administrative_Duration", title="Distribution of the Time Spent on Administrative Pages")

fig.update_layout(
    legend_title_text = "Administrative_Duration",
    yaxis_title = "Frequency",
    xaxis_title = "Total Time Spent on Administrative Pages"
)

fig.show()

### Informational

In [10]:
fig = px.histogram(online_shoppers, x="Informational", title="Distribution of the Number of Informational-Related Page Views")

fig.update_layout(
    legend_title_text = "Informational",
    yaxis_title = "Frequency",
    xaxis_title = "Informational Page Views"
)

fig.show()

### Informational_Duration

In [11]:
fig = px.histogram(online_shoppers, x="Informational_Duration", title="Distribution of the Time Spent on Informational Pages")

fig.update_layout(
    legend_title_text = "Informational_Duration",
    yaxis_title = "Frequency",
    xaxis_title = "Total Time Spent on Informational Pages"
)

fig.show()

### ProductRelated

In [12]:
fig = px.histogram(online_shoppers, x="ProductRelated", title="Distribution of the Number of Producted-Related Page Views")

fig.update_layout(
    legend_title_text = "ProductRelated",
    yaxis_title = "Frequency",
    xaxis_title = "Product-Related Page Views"
)

fig.show()

### ProductRelated_Duration

In [13]:
fig = px.histogram(online_shoppers, x="ProductRelated_Duration", title="Distribution of the Time Spent on Product Related Pages")

fig.update_layout(
    legend_title_text = "ProductRelated_Duration",
    yaxis_title = "Frequency",
    xaxis_title = "Total Time Spent on Product-Related Pages"
)

fig.show()

### BounceRates

In [14]:
fig = px.histogram(online_shoppers, x="BounceRates", title="Distribution of the Bounce Rates")

fig.update_layout(
    legend_title_text = "BounceRates",
    yaxis_title = "Frequency",
    xaxis_title = "Bounce Rates"
)

fig.show()

### ExitRates

In [15]:
fig = px.histogram(online_shoppers, x="ExitRates", title="Distribution of the Exit Rates")

fig.update_layout(
    legend_title_text = "ExitRates",
    yaxis_title = "Frequency",
    xaxis_title = "Exit Rates"
)

fig.show()

### PageValues

In [16]:
fig = px.histogram(online_shoppers, x="PageValues", title="Distribution of the Page Values")

fig.update_layout(
    legend_title_text = "PageValues",
    yaxis_title = "Frequency",
    xaxis_title = "Page Values"
)

fig.show()

### SpecialDay

In [17]:
fig = px.histogram(online_shoppers, x="SpecialDay", title="Distribution of the Special Day Values")

fig.update_layout(
    legend_title_text = "SpecialDay",
    yaxis_title = "Frequency",
    xaxis_title = "Special Day Values"
)

fig.show()

In [18]:
counts = online_shoppers.groupby(["Revenue", "SpecialDay"]).size().reset_index(name="Count")
counts["Percentage"] = (counts["Count"] / counts.groupby("Revenue")["Count"].transform("sum")) * 100
counts

    Revenue  SpecialDay  Count  Percentage
0     False         0.0   9248   88.735367
1     False         0.2    164    1.573594
2     False         0.4    230    2.206870
3     False         0.6    322    3.089618
4     False         0.8    314    3.012857
5     False         1.0    144    1.381693
6      True         0.0   1831   95.964361
7      True         0.2     14    0.733753
8      True         0.4     13    0.681342
9      True         0.6     29    1.519916
10     True         0.8     11    0.576520
11     True         1.0     10    0.524109

### Month

In [19]:
fig = px.histogram(online_shoppers, x="Month", title="Distribution of the Sessions Collected per Month")

fig.update_layout(
    legend_title_text = "Month",
    yaxis_title = "Frequency"
)

fig.show()

### OperatingSystems

In [20]:
fig = px.histogram(online_shoppers, x="OperatingSystems", title="Distribution of the Different Types of Browsers")

fig.update_layout(
    legend_title_text = "OperatingSystems",
    yaxis_title = "Frequency"
)

fig.show()

### Browser

In [21]:
fig = px.histogram(online_shoppers, x="Browser", title="Distribution of the Different Types of Browsers")

fig.update_layout(
    legend_title_text = "Browser",
    yaxis_title = "Frequency"
)

fig.show()

### Region

In [22]:
fig = px.histogram(online_shoppers, x="Region", title="Distribution of the Different Types of Regions")

fig.update_layout(
    legend_title_text = "Region",
    yaxis_title = "Frequency"
)

fig.show()

### TrafficType

In [23]:
fig = px.histogram(online_shoppers, x="TrafficType", title="Distribution of the Different Types of Trafic")

fig.update_layout(
    legend_title_text = "TrafficType",
    yaxis_title = "Frequency",
    xaxis_title = "Traffic Type"
)

fig.show()

### VisitorType

In [24]:
fig = px.pie(online_shoppers, names="VisitorType", title="Distribution of the Different Types of Customers")

fig.update_layout(
    legend_title_text = "VisitorType"
)

fig.show()

### Weekend

In [25]:
fig = px.pie(online_shoppers, names="Weekend", title="Distribution of Sessions on the Weekend")

fig.update_layout(
    legend_title_text = "Weekend"
)

fig.show()

## Target Label

### Revenue

In [26]:
fig = px.pie(online_shoppers, names="Revenue", title="Class Imbalance: More Sessions without Revenue")

fig.update_layout(
    legend_title_text = "Revenue"
)

fig.show()